- name: Set Hostname
  ansible.builtin.shell: set-hostname frontend

- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Include App Pre-requisites
  ansible.builtin.import_role:
    name: common
    tasks from: app-prereq.yml

- name: Copy expense config file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Start Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes